### ISSUE TITLE
landing page is not fully fit to screen

### ISSUE THREAD

**Issue by FezanMuhammadAli** [hars-21/Project-Metis#1]
although site is under construction but your landing page is not fully fitting in the screen. below you can check it
![1](https://github.com/user-attachments/assets/47e10e6b-0f91-472b-b234-362591648217)

also your menu button on responsiveness don't look fine.

![2](https://github.com/user-attachments/assets/9ed3382e-3138-4694-906a-a5a25c16db8e)

![3](https://github.com/user-attachments/assets/c7282882-e8be-4bfe-a6f3-fde8fa168ae1)

I can work on it if you assign to me.

**Comment by hars-21** [comment]
Proceed! Please create the PR in the develop branch.
